name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t lahiruyasas/weather-app .
    - name: Push to Dockerhub
      run: docker push lahiruyasas/weather-app:latest

      deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment happens after the build job

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Deploy to Vercel
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}  # Optional
      run: npx vercel --prod --token=$VERCEL_TOKEN --project-id=$VERCEL_PROJECT_ID --team-id=$VERCEL_TEAM_ID
