name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        docker build \
         --build-arg REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} \
         --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
         --build-arg REACT_APP_ICON_URL=${{ secrets.REACT_APP_ICON_URL }} \
         -t lahiruyasas/weather-app .
    - name: Push to Dockerhub
      run: docker push lahiruyasas/weather-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: pull image from docker hub
        run: docker pull lahiruyasas/weather-app:latest
      - name: delete old container
        run: docker rm -f weatherAppContainer
      - name: run docker container
        run: docker run -d -p 3000:80 --name weatherAppContainer lahiruyasas/weather-app:latest

   
